### PR TITLE
Implement two-factor authentication

### LINKED ISSUE #18: A very important issue

### PR DESCRIPTION
**Pull request by PeuTit**
The purpose of this feature is to allow users to setup two-factor authentication on their account via Google Authenticator.

Closes: KEYP-1

38

### CODE REVIEW

**Comment by PeuTit** [comment]
This is a comment on a PR

**Comment by PeuTit** [comment]
I need to add a few things to this PR to make it 200% perfect.

- [ ] Test coverage
- [ ] CI/CD
- [ ] Rule for contributions

**Review by alachaum — APPROVED** [review]
👍

**Review by alachaum — APPROVED** [review]
👍

**Review by alachaum — APPROVED** [review]
👍

**Review by alachaum — APPROVED** [review]
👍

**Review by alachaum — APPROVED** [review]
👍

**Review by alachaum — APPROVED** [review]
👍

**Review by alachaum — APPROVED** [review]
👍

**Review by pixernot — DISMISSED** [review]
I want to change a few things

**Review by alachaum — DISMISSED** [review]
I say it's fine. Let's go with it.

**Review by pixernot — DISMISSED** [review]
Code must be refactored.

**Review by alachaum — DISMISSED** [review]
👍

**Review by alachaum — DISMISSED** [review]
All good for me

**Review by pixernot — DISMISSED** [review]
👍

**Review by pixernot — CHANGES_REQUESTED** [review]
Need to rework

**Review by pixernot — APPROVED** [review]
It's good now

**Review by alachaum — DISMISSED** [review]
Approved

**Review by alachaum — DISMISSED** [review]
👍

**Pull request closed without merging**
